name: GitHub Actions TEST2
on: push
jobs:
  sample-action-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "ğŸ This job's status is ${{ job.status }}."
