name: GitHub Actions TEST2
on: push
jobs:
  sample-action:
    runs-on: linux-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "ğŸ This job's status is ${{ job.status }}."
